name: zap_architecture_flutter
description: Flutter helper package for the original zap_architecture plugin.
version: 0.0.2
homepage: musausman.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  zap_architecture: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
