name: zap_architecture_flutter
description: Flutter helper package for the original zap_architecture plugin.
version: 0.0.3
homepage: https://musausman.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info: 0.4.3+2 
  zap_architecture: 0.1.0
  dio: 3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
