name: zap_architecture_flutter
description: Flutter SDK for ZAP built on top of the core zap_architecture library.
version: 0.1.0+1
homepage: https://musausman.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info: 0.4.3+4
  zap_architecture: 0.2.0+1
  dio: ^3.0.10
  get: ^3.24.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
